# Generated by Django 3.2.6 on 2022-03-08 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissional',
            options={'verbose_name': 'Profissionai'},
        ),
    ]
