# Generated by Django 3.2.6 on 2022-03-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_profissional_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissional',
            options={'verbose_name': 'Profissional '},
        ),
        migrations.AlterField(
            model_name='profissional',
            name='data_cadastro',
            field=models.DateField(auto_now=True),
        ),
    ]
