# Generated by Django 3.2.6 on 2022-03-08 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20220308_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='data_cadastro',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
