# Generated by Django 3.2.6 on 2022-04-07 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('cadastro', '0004_alter_profissional_data_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='profissional',
            options={'verbose_name': 'Profissional'},
        ),
        migrations.AddField(
            model_name='profissional',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profissional',
            name='especialidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cadastro.especialidades'),
        ),
    ]
