# Generated by Django 3.2.6 on 2022-04-11 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20220407_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidades',
            options={'verbose_name': 'Especialidade'},
        ),
        migrations.AddField(
            model_name='profissional',
            name='descricao',
            field=models.TextField(default=7),
            preserve_default=False,
        ),
    ]
